[package]
license     = "MIT"
edition     = "2024"
version     = "1.0.0-beta.1"
name        = "retry_core"
repository  = "https://github.com/cainthebest/retry_core"
authors     = ["cainthebest <https://github.com/cainthebest>"]
description = "A retry library for fallible blocking and async operations"
keywords    = ["retry", "async", "blocking", "resilience", "no-std"]
categories  = ["asynchronous", "no-std::no-alloc"]

[profile.release]
codegen-units = 1
opt-level     = 3
lto           = 'fat'
debug         = false

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[[example]]
name = "sync_args"
path = "examples/sync/args.rs"

[[example]]
name = "sync_zero_arg"
path = "examples/sync/zero_arg.rs"

[[example]]
name = "tokio_args"
path = "examples/tokio/args.rs"

[[example]]
name = "tokio_zero_arg"
path = "examples/tokio/zero_arg.rs"
